# Generated by Django 5.1.4 on 2024-12-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('content', models.CharField(max_length=2000)),
                ('url', models.URLField()),
            ],
        ),
    ]
